version: "3.9"

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: dockerfile.dev
    restart: always
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
      - ./.next:/app/.next
    ports:
      - 3000:3000
