FROM node:20.12.1-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

COPY . .

RUN npm install

RUN npm run build

RUN npx prisma generate

EXPOSE 4000

CMD [ "npm" , "run", "start:dev" ]