version: '3.9'

services:
  backend:
    container_name: nestapp
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 3001:3001
    depends_on:
      - db

  db:
    image: postgres:16.2-alpine
    container_name: postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  db:
