import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { UiButton } from "@/shared/UiButton";
import { UiInput } from "@/shared/UiInput";
import { Box, Container, TextField } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container
        sx={{
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
          height: "100%",
        }}
      >
        <Box
          sx={{
            my: 4,
            display: "flex",
            flexDirection: "column",
            justifyContent: "center",
            alignItems: "center",
            gap: "10px",
          }}
        >
          <h1>Sign In</h1>
          <UiInput label={"Email"} />
          <UiInput label={"Password"} type="password" />
          <UiButton variant="contained">Confirm</UiButton>
        </Box>
      </Container>
    </>
  );
}
